[phases.setup]
nixPkgs = ["python3", "python3Packages.pip"]
aptPkgs = ["libpq-dev", "gcc"]

[phases.install]
cmd = "pip install -r requirements.txt"

[phases.build]
cmd = "python manage.py migrate --noinput"

[start]
cmd = "bash start.sh"