[phases.setup]
packages = ["python3", "python3Packages.pip", "libpq"]

[phases.install]
commands = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
commands = [
  "python manage.py migrate --noinput"
]

[phases.start]
command = "bash start.sh"